title: Воно працювало
email: nikolay@ponich.com
description: >- # this means to ignore newlines until "baseurl:"
  Смітник моїх технічних нотаток
baseurl: ""
url: ""
twitter_username: PonychM
github_username:  ponich

# Build settings
theme: minima
plugins:
  - jekyll-feed
